name: Publish Documentation
on:
    workflow_dispatch:
    push:
      branches:
        - master

jobs:

  ###################################################
  # DOCS
  ###################################################

  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Publish-Documentation
      uses: cake-build/cake-action@v2
      with:
        script-path: recipe.cake
        target: Publish-Documentation
        cake-version: tool-manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STATIQ_GITHUB_TOKEN: ${{ secrets.STATIQ_GITHUB_TOKEN }}
        STATIQ_DEPLOY_BRANCH: ${{ secrets.STATIQ_DEPLOY_BRANCH }}
        STATIQ_DEPLOY_REMOTE: ${{ secrets.STATIQ_DEPLOY_REMOTE }}
